Upgraded to React 18, changed JsxParser (Fixes JsxParser is not a valid Jsx Element)
TroyAlford/react-jsx-parser pull request #256
Opened 2023-12-16 10:01 UTC by EliteByte

Strictly upgraded a few modules in order to get it working with React 18 including an enzyme alternative for React 18

2024-02-19 06:49 UTC, TroyAlford requested changes
I left some comments - sorry for the slow response. I'm happy to get this merged once updated.

I do not see any benefit in moving to a functional component, and lots of downside. I will not approve a PR that does that. That said, I am perfectly happy to have a separately named functional component as a wrapper which renders the class component that's already here. I'm not sure if that provides a benefit, however.

Also, Circle CI is not passing with this build. Not sure why at the moment - I assume the build works for you?

2024-02-19 06:49 UTC, TroyAlford commented on source/components/JsxParser.tsx
> +			? resolvePath(this.props.components, name)
This change shouldn't be needed, as components is already restructured above

2024-02-19 06:49 UTC, TroyAlford commented on source/components/JsxParser.tsx
> +interface ForwardRefComponentProps {
This doesn't seem terribly useful as a type. Probably better just to use `any` or `unknown` here instead of essentially just defining a `Record`

2024-02-19 06:49 UTC, TroyAlford commented on source/components/JsxParser.tsx
> +const ForwardRefComponent = React.forwardRef<any, ForwardRefComponentProps>((properties, ref) => {
Small thing, but I'd love to have this in a separate file, and call it sometime like just ForwardRef

2024-02-19 06:49 UTC, TroyAlford commented on source/components/JsxParser.tsx
> +			.split(' ')])].filter(Boolean).join(' ')
This line is already lamentably hard to read. I'd prefer we either make it readable or leave it alone. Breaking the [ ] onto separate lines makes it even more unclear, IMHO.

2024-02-19 06:49 UTC, TroyAlford commented on source/components/JsxParser.tsx
> +				)
I don't see any benefit to this change. It introduces a fragment where one isn't needed, and uses create element where it also isn't needed.

2024-02-19 06:49 UTC, TroyAlford commented on source/demo.tsx
> +import { createRoot } from 'react-dom/client'
This is the only substantial change here, to support the latest rendering method. Could we please refer the rest? The demo script is designed to go with it's host html - I don't see much reason to safety check whether that hard coded page has an element on it. Also, this change appears to have altered the indentation and formatting quite a bit

2024-04-11 07:28 UTC, frandevel commented
Nice that this is so close to happen!
I'd love to hear about the end of this story. Really interested in the outcome, as we also need to upgrade as soon as possible

2024-06-21 07:41 UTC, frandevel commented
I just pushed the necessary changes that @TroyAlford suggested. Please feel free to check them and consider merging the PR. 
I would be glad to also test it for React 19, so we're more up-to-date

2024-06-21 08:57 UTC, frandevel commented
@elitebyte , you have a PR ready to have the suggestions integrated. Feel free to ping me to discuss anything.
Thanks for the time spent.

2024-07-01 00:26 UTC, TroyAlford commented
@frandevel @elitebyte unfortunately, I'm trying to get tests to pass locally with a minimal subset of these changes, but something is wrong with the function parsing algorithms. Getting React 18+ working seems fine, and requires very little of what's been changed here, but I don't want to inadvertently create a regression with other features.

2024-07-01 01:30 UTC, TroyAlford commented
I am closing this PR as dead. I have pushed some changes to the `develop` branch which take the relevant parts and commit them. I'll work on releasing a new version to test with Soon™

2024-07-01 01:30 UTC, closed without merging